spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 192.168.1.92
    port: 6379

demo:
  #Database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 10000
  secret: demotest
  appKey: kr.co.samsungsvc.spnsanalyzer


---


spring:
  profiles: local
  output:
    ansi:
      enabled: ALWAYS

demo:
  #Homepage URL
  url:
    user: http://localhost:9191
  #Database
  datasource:
    url: jdbc:mysql://192.168.1.92:3306/sesa?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: sesa
    password: sesa202005!
  #File Upload Directory Path
  file-upload:
    temp-dir: C:/attach/temp
    save-dir: C:/attach/save


---


spring:
  profiles: dev

demo:
  #Homepage URL
  url:
    user: http://localhost:9191
  #Database
  #spring 2.0 + 이상 부터 serverTimezone=UTC 추가
  datasource:
    url: jdbc:mysql://192.168.1.92:3306/sesa?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: sesa
    password: sesa202005!
  #File Upload Directory Path
  file-upload:
    temp-dir: /data/demo/attach/temp
    save-dir: /data/demo/attach/save


---


spring:
  profiles: prod
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379

demo:
  #Homepage URL
  url:
    user: http://localhost:18080
  #Database
  #spring 2.0 + 이상 부터 serverTimezone=UTC 추가
  datasource:
    url: jdbc:mysql://20.8.121.69:3306/sesa?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: sesa
    password: Sesa2020!@
  #File Upload Directory Path
  file-upload:
    temp-dir: /svcwas/demo/attach/temp
    save-dir: /svcwas/demo/attach/save